stages:
  - scc
  - checkLicense
  - build_Andes
  - oss
  - misspellChecking
  - sensitive_word_check

scc:
  stage: scc 
  tags:
    - LINUX
  dependencies: []
  script:
    - echo "Enter scc stage"
    - scc | tee scc.txt
    - bash /usr/bin/scc_calc.sh
    - echo "The End SCC result:"
    - cat scc.txt
  artifacts:
    paths:
    - scc.txt
  when: manual #always

checkLicense:
  variables:
    CODE_COMPILE_ARCH: 'EAGLE_ANDES'
    COV_PF_CATALOG: 'BLE'
  stage: checkLicense
  tags:
    - LINUX
  allow_failure: yes
  dependencies: []
  before_script:
  script:
    - date
    - check_license
    #- generat_license_list 
    - date
    - ls

  artifacts:
    when: always
    paths:
    - "mismatch_license.txt"
    - "no_license*.txt"
    - "unknow_type_file.txt"
  when: manual #always

build_Andes:
  variables:
    ECLIPSE_PROJECT_PATH: './eagle_ble_sdk'
    ECLIPSE_PROJECT_NAME: 'B91_ble_multi_conn_sdk'
    ECLIPSE_BUILD_TARGET: 'B91_demo'         
  stage: build_Andes
  tags:
    - TELINKIDE_LINUX
  dependencies: []
  before_script:
  script:
    - date
    - echo "--------------- Will build Demo -----------------"
    - echo $ECLIPSE_PROJECT_PATH --- $ECLIPSE_PROJECT_NAME/$ECLIPSE_BUILD_TARGET
    - $ANDESRISCV_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import $ECLIPSE_PROJECT_PATH -cleanBuild $ECLIPSE_PROJECT_NAME/$ECLIPSE_BUILD_TARGET
    - date
  artifacts:
    paths:
    - "B91_ble_multi_conn_sdk/B91_demo/output/objdump.txt"
    - "b91m_ble_multiconn_sdk/B91_demo/output/*.bin"
  when: manual

oss:
  tags:
    - OSS
  stage: oss
  dependencies: []
  script:
    - oss_checking .
  artifacts:
    paths:
    - scan_result
  when: manual      
  
  
misspellChecking:
  stage: misspellChecking
  tags:
    - LINUX
  dependencies: []
  script:
    - echo "--------------- Begin ------------------------"
    - misspell-check
    - echo "---------------- End -----------------------"
  artifacts:
    when: on_failure
    paths:
    - misspell_result.txt
  when: manual    # Just check, ignore fail

sensitive_word_check:
  stage: sensitive_word_check 
  tags:
    - LINUX
  dependencies: []
  script:
    - grep -E "(esb|nrf|nordic|Shock[ ]*Burst)" . -inr
    - > 
      if [ $? == 0 ]; then
        exit 1
      fi
  when: manual 
